os: osx
osx_image: xcode13.1
language: generic
branches:
    only:
    - master
    - /^v\d.*/
env:
- TOXENV=py2 BREW_PYTHON=python@2 PYTHON=python2
- TOXENV=py-flake8 BREW_PYTHON=python@2 PYTHON=python2
- TOXENV=py3 BREW_PYTHON=python PYTHON=python3

before_install:
- brew update
install:
- brew ls $PYTHON || brew install $BREW_PYTHON
- $PYTHON -m pip install tox coverage coveralls
- if [ $PYTHON == "python2" ]; then ln -fs /usr/local/bin/python2 /usr/local/bin/python; ln -fs /usr/local/bin/pip2 /usr/local/bin/pip; fi
- sudo mkdir -p /usr/local/man && sudo chown $USER /usr/local/man
before_script:
- umask 0022
script:
- tox
after_success:
- coverage combine
- coveralls

deploy:
  provider: pypi
  user: tdsmith
  password:
    secure: aMbgpTpEpojo1OYq8JDhg3Qgo3/c5BoKGeHwm0UJ070kn7sR3K4zwsQ1ybq9DsM6oL+Nv9vAfbyyQmHyuDf0OoXt0nEPR/vkbwURrrXONmQ5NUvLULnQTdfwvNbHY3TaQlTbrloCVhr5CECDKckd+6SHcJDfjwsSaVK0wSWNq8Y=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: tdsmith/homebrew-pypi-poet
    condition: $TOXENV = py2
